version: '3.8'
services:
  backend:  
    image: nikilasilva/eventra-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000