name: Eventra CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "18"
            cache: "npm"
            cache-dependency-path: "**/package-lock.json"

        - name: Install Backend Dependencies & Run Tests
          run: |
            cd backend
            npm install
            npm test

        # - name: Install Frontend Dependencies & Build
        #   run: |
        #     cd frontend
        #     npm install
        #     npm run build

        - name: Login to Docker Hub
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Backend Docker image
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./backend/Dockerfile
            push: true
            tags: yourdockerhubusername/eventra-backend:latest
